name: md2pdf

on: push

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/latex
        with:
          args: --pdf-engine=xelatex build.md -o output/build.pdf
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: output